apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    name: node
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer